---
# tasks file for docker
- name: Remove old packages
  apt:
    pkg: docker,docker-engine,docker.io
    state: absent
    purge: yes

- name: Installing Dependencies
  apt:
    pkg: apt-transport-https,ca-certificates,curl,software-properties-common
    state: present
    update_cache: yes

- name: Official Docker Repo GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: Install Docket CE
  apt:
    pkg: docker-ce
    update_cache: yes
  notify:
    - Start Docker

- name: Docker Compose
  get_url: 
    url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755	

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes
